### ISSUE TITLE
Listener receives no messages 

### ISSUE THREAD

**Issue by julian533** [fujitatomoya/k8s_ros_sample#1]
I have tested the repo on a setup with 2 worker nodes and 1 master node, , which all run. For this I use Kubeadm with a weave overlaying network 
```
NAME            STATUS   ROLES    AGE   VERSION
w-robolab-p11   Ready    <none>   15h   v1.17.4
w-robolab-w05   Ready    <none>   15h   v1.17.4
w-robolab-w06   Ready    master   15h   v1.17.4
```
ros2-listener-0 and ros2-talker run on one worker node, ros2-listener-1 runs on the 2 worker node. The listener pod (ros2-listener-0), which runs on the same node as the master, receives all messages from the talker, but the listener on the 2 node (ros2-listener-1) does not receive any messages. When I enter kubectl logs, no output is returned.
```
kubectl get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE   IP           NODE            NOMINATED NODE   READINESS GATES
ros2-listener-0-7b9596449c-6vkmn   1/1     Running   0          15h   10.244.2.8   w-robolab-p11   <none>           <none>
ros2-listener-1-5f99bdffff-p5zbs   1/1     Running   0          15h   10.244.1.5   w-robolab-w05   <none>           <none>
ros2-talker-7b6cd5cf86-82rt2       1/1     Running   0          15h   10.244.2.7   w-robolab-p11   <none>           <none>
```
as already mentioned i use weave and it seems to be configured correctly. 
```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
default       ros2-listener-0-7b9596449c-6vkmn        1/1     Running   0          15h
default       ros2-listener-1-5f99bdffff-p5zbs        1/1     Running   0          15h
default       ros2-talker-7b6cd5cf86-82rt2            1/1     Running   0          15h
kube-system   coredns-6955765f44-2frx4                1/1     Running   0          16h
kube-system   coredns-6955765f44-smm4h                1/1     Running   0          16h
kube-system   etcd-w-robolab-w06                      1/1     Running   0          16h
kube-system   kube-apiserver-w-robolab-w06            1/1     Running   0          16h
kube-system   kube-controller-manager-w-robolab-w06   1/1     Running   0          16h
kube-system   kube-proxy-kwstt                        1/1     Running   0          16h
kube-system   kube-proxy-lbjc4                        1/1     Running   0          16h
kube-system   kube-proxy-z4m9h                        1/1     Running   0          16h
kube-system   kube-scheduler-w-robolab-w06            1/1     Running   0          16h
kube-system   weave-net-cs6d7                         2/2     Running   0          16h
kube-system   weave-net-j8hkt                         2/2     Running   0          16h
kube-system   weave-net-tvq9w                         2/2     Running   0          16h
```
Does anyone have any idea what the problem might be?

**Comment by fujitatomoya** [comment]
@julian533 

thanks for the issue,

may i suggest the following as 1st step,

- login ros2-listener-1-5f99bdffff-p5zbs container see if ros2 dds connection is online.

```
k8smaster> kubectl exec -it ros2-listener-1-5f99bdffff-p5zbs -- /bin/bash
container> ros2 node lit
container> ros2 topic list
container> ros2 topic echo /chatter
```

**Comment by julian533** [comment]
@fujitatomoya 
 as you suggested, I first logged into the ros2-listener-1-f6f6bc864-ph7fp (I restarted the deplyoment, hence a different name for the pod).
ros2 node list, shows only /listener and no /talker 
```
root@ros2-listener-1-f6f6bc864-ph7fp:/# ros2 node list
/listener
```
ros2 topic list shows the following output :
```
root@ros2-listener-1-f6f6bc864-ph7fp:/# ros2 topic list
/chatter
/parameter_events
/rosout
```
and as expected ros2 topic echo/chatter shows no output: 
```
root@ros2-listener-1-f6f6bc864-ph7fp:/# ros2 topic echo /chatter
```
I tried stop the ros2 daemon and restart it on each system, because it had worked for some people with similar problems (see https://answers.ros.org/question/304373/ros2-nodes-can-not-see-one-another-via-network/), but it did not solve the problem for me

**Comment by julian533** [comment]
@fujitatomoya 

I have found a workaround to solve the problem. I configured the pods with ```hostNetwork: true```. Now all Pods receive the messages of the talker.

 I'm not sure if this is the best workaround, but at least it seems to work. So from my side the issue could be closed.

**Comment by fujitatomoya** [comment]
@julian533 

it is really weird situation, node cannot be discovered but topic can be? but if using host network interface is good for you, i am closing this issue.

**Comment by julian533** [comment]
@fujitatomoya 
Yes it's really a very strange behavior. But with host network interface it works now.
